USSF-ORBIT/ussf-portal-cms

keystone.ts

This is an attempt to fix the database url parsing error happening on the AWS side. Thanks to @suzubara  for the suggestion!
cc @esacteksab

dev: Add string interpolation to db url

---

CHANGELOG.md
Dockerfile
docker-compose.e2e.yml

* Add migration for existing cms data ([#31](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/31)) ([d16877e](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/d16877e0371873aaa1a2c2a2ab22aac9994728b8))
* Add Bookmark, Collection schema ([#30](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/30)) ([bdc9836](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/bdc98360adafcfe175f576d51a05cb9fab2e6780))
* Log in with portal client user ([#17](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/17)) ([738d433](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/738d43353ec6572f62cb0c9ecf53a9599bd544da))
* Redirect to portal login page if not logged in ([#21](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/21)) ([6f41c49](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/6 …

chore(release): 1.0.0

---

migrations/20220421163348_create_events/migration.sql
schema.graphql
schema.prisma
src/lists/Bookmark.ts
src/lists/Collection.ts
src/lists/Event.ts
src/lists/User.ts
src/schema.ts
src/util/logging.ts
src/util/tracking.ts

[WIP] Add event logging

---

scripts/add-rds-cas.sh

Just like https://github.com/USSF-ORBIT/ussf-portal-client/pull/639

chore: updating rds cert for us-west-gov-1

---

.github/workflows/dev-aws-ecr.yml
.github/workflows/man-build-push-c1.yml
.github/workflows/man-build-push-deploy-dev-aws.yml

This had a typo on the existing C1 job. I also reworded job names for consistency as well as added a manual C1 job, just in case.

ci: a little cleanup and consistency in convention. 

---

.dockerignore
.gitignore
Dockerfile
package.json
yarn.lock

Reverts #49 but I want to test #51 first prior to merging this.

revert: "chore: make Docker layers and overall image size smaller (#49)"

---

.github/workflows/e2e-ci.yml
.github/workflows/node-ci.yml

Like the portal-client PR, this does it to CMS side of things. I also updated the actions while I was here.

ci: a dynamic version rather than hard-coded version

---

.github/CODEOWNERS

chore: adding Tall John to codeowners

---

.github/CODEOWNERS

chore: removing Suz from codeowners

---

.github/CODEOWNERS

Removes Noah from code owners reversing sc-713

chore: remove Noah as temporary code owner

---

CHANGELOG.md
package.json

chore(release): 1.4.1

---

renovate.json

Group them together rather than individual PR's for each action.

ci: group github action updates

---

CHANGELOG.md
package.json

chore(release): 1.4.2

---

CHANGELOG.md
package.json

* update docker build to embed info for sysinfo response ([#120](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/120)) ([f5691f0](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/f5691f00aedb02819cfb48416b663e885a899cdb))

chore(release): 1.4.3

---

.github/workflows/e2e-ci.yml

- add statement so reusable workflow inherits secrets from this repo
---
---

ci: e2e inherit secrets

---

CHANGELOG.md
package.json

chore(release): 1.4.5

---

.github/workflows/dev-aws-ecr.yml

- run Trivy scan on CMS container image after push to ECR in DEV AWS
- upload Trivy scan results to Github Security Tab
---

ci: add trivy scanning

---

.github/workflows/dev-aws-ecr.yml

ci: trivy scan cms

---

package.json
yarn.lock

Hopefully address most of the open Dependabot alerts

security: update undici to 5.5.1

---

package.json
yarn.lock

Should handle this vuln https://github.com/USSF-ORBIT/ussf-portal-cms/security/dependabot/7

security: upgrades busboy which should update dicer

---

yarn.lock

This PR reverts changes made to the `yarn.lock` file that were not triggered by any changes in `package.json`.
Our best educated guess is `yarn upgrade` was ran at some point, updating nested dependencies in the `yarn.lock` file that were not reflected in `package.json`, and one of them causes a bug in our local dev environment.
One theory is it's one of the dev dependencies, which is why it works in Docker but not locally.
Please test locally with `yarn dev` and make sure the app works as expected.
Run the cms and portal locally and make sure the server doesn't time out + everything works as expected.
Let me know if you have any issues with yarn overwriting the lockfile when running `yarn` or `yarn install`. Try it as you normally would at first, but you can also add `--frozen-lockfile` …

chore: Revert lockfile to fix main local dev and keep undici updates

---

CHANGELOG.md
package.json

chore(release): 1.4.7

---

CHANGELOG.md
package.json

chore(release): 1.4.8

---

src/lists/Byline.test.ts
src/lists/Byline.ts
src/lists/Location.test.ts
src/lists/Location.ts

- Add character limit of 50 for Byline and Location
---
Run both the portal client and cms, login and try to create both a byline and a location with more than 50 characters. Also try updating an existing byline or location with more than 50 characters. You should see an error message in the Keystone UI and be prevented from saving changes.
Also make sure all tests pass:
- `yarn test`
In cms repo:
- `yarn services:up && yarn dev`
In portal client on main:
- `yarn dev`
---
- ... 
- Performed [a11y …

dev: Add character limit to Byline and Location

---

CHANGELOG.md
package.json

chore(release): 1.5.2

---

CHANGELOG.md
package.json

chore(release): 1.5.3

---

.github/workflows/cache-to-ecr.yml
Dockerfile

- Re-move ADD command in favor of RUN command for downloading OpenSSL file, as per best practices. https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
- Combine run commands to decrease the number of cache layers. https://docs.docker.com/build/cache/#combine-commands-together-wherever-possible
- Update buildx and buildkit in E2E tests using setup-buildx-action
- remove superfluous meta actions from `/.github/workflows/cache-to-ecr.yml` that do not matter in the caching mechanism and might actually cause cache invalidation in the future
---
---
- ... 
- Performed [a11y …

build: optimize builder layer for cache efficiency

---

package.json
yarn.lock

- Resolve `undici` to `5.20.0` to mitigate [Dependabot #31](https://github.com/USSF-ORBIT/ussf-portal-cms/security/dependabot/31) and [Dependabot #30](https://github.com/USSF-ORBIT/ussf-portal-cms/security/dependabot/30)
---
---
- ... 
---

chore(deps): resolve undici to 5.20.0

---

scripts/add-dod-cas.sh

- DoD Cyber Exchange has released a new Root CAs Bundle. This has replaced the, likely, expired bundle that we have been using, of which we no longer have access to download. The Certs allow us to connect to Artifactory.
---
---
---
- ... 
---

chore: update DoD Root CAs Bundle

---

CHANGELOG.md
package.json

* **deps:** update dependency @keystone-6/fields-document to v5.0.2 ([#281](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/281)) ([aaca0a6](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/aaca0a6ede262b731a78a4bd9a117b979f8f797d))

chore(release): 1.8.1

---

.github/workflows/build-push-c1-art.yml

- updated the `build-push-c1-art.yml` workflow with `docker/login-action` so we don't have to use insecure password entry in a `docker login` shell command 
- Note: for some reason, the `docker/build-push-action` crashes if the "push" option is set to `true`. This looks like it's a buildx issue in one of our image's layers that prevents the action from completing. Not an issue, as we can continue to use `docker push` shell command in this repo.
---
Successfully tested in this workflow dispatch: https://github.com/USSF-ORBIT/ussf-portal-cms/actions/runs/4576868119 
---
- ... 
- Performed [a11y …

ci: replace c1-art workflow shell cmds with docker actions

---

renovate.json

- Some updates to keystone require graphql schema changes. This breaks the renovate/dependency branch. Creating a separate group for keystone updates will make the renovate/dependency branch more reliable
---
---
- ... 
---

chore: create a keystone renovate group

---

renovate.json

- enable lockfile maintenance by renovate
- remove erroneously added node filter in keystone group
- add preset group for linters
---
---
- ... 
---

chore(deps): enable lockfile maintenance and remove erroneously added package name filter

---

renovate.json

- @prisma/client updates are to be separated from other dependencies in renovate/dependencies PRs so those PRs have a better chance of passing checks.
- All prisma minor and major updates will be kept separate. Patch updates will be allowed to be grouped with other dependencies as patches should be OKAY with dependency constraints.
- The reasoning is that we want to essentially pin version 4.3.1 without actually pinning it, because we want Renovate to keep pulling prisma updated version while not breaking out renovate/dependencies branch all the time. Version 4.3.1 
is the latest version which is not failing 
unit tests and e2e tests. @prisma/client@4.9.0 fails jest tests (only in GH though). But any version above 4.3.1 crashes when running in a container alongside Keystone. This is …

chore: separate prisma updates from other dependencies

---

CHANGELOG.md
package.json

* Filter search results by single tag or label ([#316](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/316)) ([1f5c7c8](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/1f5c7c8ce617d781431077e12559259948099d1c))
* **deps:** update keystone ([#314](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/314)) ([4dec14a](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/4dec14a06eb67336e1728c05cbe16401e23872a9))
* order renovate packagerules in ascending order of importance ([#311](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/311)) ([8340d13](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/8340d135a8f5e1baba2d5901fe5c256bee7096f0))
* update pr tempate ([#318](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/318)) …

chore(release): 1.9.0

---

.github/workflows/cache-to-ecr.yml

- Change the docker repository `cache-to` target to a new ECR repository named `docker-build-cache` which will be a dedicated repository for CMS and Client image build caches
- This will improve our ECR's reliability and costs because we can use better written ECR Lifecycle Policies when the image tags are more predictable and there is a different repo for different functions.
---
The updated workflow has a successful test run here: https://github.com/USSF-ORBIT/ussf-portal-cms/actions/runs/4766715452/jobs/8474080277
```sh
yarn dev
yarn dev
```
---
---

build: use dedicated docker-build-cache ECR

---

.github/workflows/build-push-c1-art.yml

- Tag Docker image for Artifactory Test and Prod repositories and push
---
For how the job runs, see Workflow Run: https://github.com/USSF-ORBIT/ussf-portal-cms/actions/runs/5018160502/jobs/8997220007
```sh
yarn dev
yarn dev
```
---
---

build: automate image copy from artifactory dev to test and prod

---

.github/workflows/build-docker-cache-artifacts.yml

- use `jq` to get the SHA from the docker image digest in a more human-readable way
---
```sh
yarn dev
yarn dev
```
---
---

refactor: use jq to get sha from docker image digest

---

package.json
yarn.lock

- fast-xml-parser resolution to address Dependabot Alert [#37](https://github.com/USSF-ORBIT/ussf-portal-cms/security/dependabot/37) and  [#39](https://github.com/USSF-ORBIT/ussf-portal-cms/security/dependabot/39)
- xml2js resolution to address Dependabot Alert [#34](https://github.com/USSF-ORBIT/ussf-portal-cms/security/dependabot/34)
---
```sh
yarn dev
yarn dev
```
---
---

fix(deps): update fast-xml-parser and xml2js (security)

---

Dockerfile

- Upgrade Docker Images from Debian 11 (bullseye) to Debian 12 (bookworm)
- Switch from using `slim` versions of Node images to regular images which have OpenSSL 3
- Remove script and dependencies for building OpenSSL 3
---
```sh
yarn dev
yarn dev
```
---
---

build: Upgrade Docker Images to Debian 12 Bookworm

---

Dockerfile

- Go back to using `slim` Node images as the regular sized images are breaking the Github Actions runners' size limit (probably due to the caching mechanisms we use which exacerbate the size of an image on disk).
---
```sh
yarn dev
yarn dev
```
---
---

build: use slim images for better optimization in gha

---

.github/workflows/release-please.yml

- Calls Release Please as a reusable Github Actions workflow
---
```sh
yarn dev
yarn dev
```
---
---

chore: call release please reusable workflow

---

.github/workflows/dev-aws-ecr.yml

- Disables Docker Buildx provenance feature which creates provenance attestations during the build process, which are then inadvertently pushed to ECR (causing 3 items to be pushed instead of just 1 image) https://docs.docker.com/build/attestations/slsa-provenance/
---
```sh
yarn dev
yarn dev
```
---
---

build: disable docker provenance

---

scripts/add-dod-cas.sh

- Change static file/directory names to have wildcards in the `add-dod-cas.sh` shell script so that minor version updates to the DoD PKI Certificate package will not break the file and directory names in the script.
- Moved the working directory of much of the script logic back one level for easier maintenance of script
---
```sh
yarn dev
yarn dev
```
---
---

build: allow all minor version updates of pkcs v5_*

---

.github/workflows/check-docker-build.yml

- Update `check-docker-build.yml` to look in local repo GHA cache instead of GHA artifacts for e2e docker cache
---
```sh
yarn dev
yarn dev
```
---
---

ci: update check-docker-build.yml workflow for new cache method

---

keystone.ts

Support for new redirect page, see https://github.com/USSF-ORBIT/ussf-portal-client/pull/1152
---
```sh
yarn dev
yarn dev
```
---
---

fix: update redirect path for portal

---

src/lib/auth.ts
src/lists/User.test.ts
src/lists/User.ts

A CMS admin can create a user and assign a role prior to that user's first login
---
Make sure that there are no other users on your local machine (at least not Ethel Neal).
Log in to the CMS as an admin:
- Click on `Users` and `Create User`
- In the `User Id` field, add in `ETHEL.NEAL.643097412@testusers.cce.af.mil`
- Select the `Author` role from the dropdown
- Click `Save`
Now you should be able to log in as Ethel Neal for the first time and have all Author permissions
Check out the e2e tests: https://github.com/USSF-ORBIT/ussf-portal/pull/342
```sh
yarn dev
yarn dev
```
---
Check out our [How to review a pull request](https://github.com/USSF-ORBIT/ussf-portal/blob/main/docs/how-to/review-pull-request.md) …

feat: Admin can create users

---

.mergify.yml

---
This is just a change to Mergify and should not affect cms

chore: edit the mergify logic to be consistent across accounts

---

.github/settings.yml
.mergify.yml

Make the e2e tests required again

chore: Add e2e tests

---

migrations/20240103174500_add_hero_image_to_landing_page/migration.sql
migrations/20240104205955_add_badge_to_landing_page/migration.sql
schema.graphql
schema.prisma
src/lists/LandingPage.ts

Add hero image support for landing pages
---
Related PRs:
https://github.com/USSF-ORBIT/ussf-portal-client/pull/1189
https://github.com/USSF-ORBIT/ussf-portal/pull/350
When creating a landing page, you should now be presented with the option to upload a hero image. You may need to destroy your local CMS and rebuild it in order for this to work because this PR adds a new migration.
```sh
yarn dev
yarn dev
```
---
---

feat: Add hero image support for landing page
