.github/workflows/build-push-c1-art.yml

Need an image before I can do anything else. This adds a GitHub Action to build the docker image, then push it to C1 Artifactory. From there, I'll create a job that transfers it from C1 Artifactory to AWS ECR.
Fixes # sc-295 sc-296

ci: sc-295 adding GHA to build/push keystone docker image to c1

---

.github/workflows/build-push-c1-art.yml
scripts/add-dod-cas.sh

Right now we can't connect to artifactory because of the DoD's self-signed certs. I believe this should add the CA's so that we can connect to artifactory and upload the docker image.

ci: adding dod cas so we can connect to artifactory

---

e2e/cypress/fixtures/example.json
e2e/cypress/integration/auth.spec.js
jest.config.js
migrations/20220328165725_add_bookmark_list/migration.sql
migrations/20220407182619_add_collection/migration.sql
migrations/20220411205656_/migration.sql
migrations/20220412141415_/migration.sql
migrations/20220412141619_/migration.sql
schema.graphql
schema.prisma
src/lists/Bookmark.ts
src/lists/Collection.ts
src/schema.test.ts
src/schema.ts

- Adds Bookmark and Collection schemas
- Lowers required test coverage down to 50% for unit tests
---
- Log into the portal as a user without CMS access (`user1 / user1pass`) and try to navigate to the CMS. You should not be able to access it.
- Log into the portal as a user with CMS access (`cmsuser / cmsuserpass`) and try to navigate to the CMS. You should be able to access it.
- While logged in as a user with CMS access, verify that you can create, read, and update Bookmarks and Collections.
- While logged in as a user with CMS access, verify that you cannot delete any Bookmarks or Collections.
Testing this PR requires running both the CMS and portal app locally:
1. Make sure you have the portal repo checked out, and the environment variable set to its path (in the CMS repo):
`export …

feat: Add Bookmark, Collection schema

---

migrations/20220412180221_sqlite_migration/migration.sql

This PR migrates existing data from embedded Keystone to our standalone instance.
* Uses a dump of the embedded Keystone sqlite db to pull out data
* Creates a prisma migration to add the data to the postgres db
Fixes #sc-291
Testing
* Run `npx prisma migrate dev` and make sure migration successfully completes
* Run portal and log in as cmsuser or cmsadmin
* Run `yarn dev` and open Keystone at localhost:3001
* Validate there are 310 new bookmarks
* Validate there are 14 new collections

chore: Migrate existing cms data to postgres

---

.github/workflows/codeql-analysis.yml

This adds [CodeQL](https://github.com/github/codeql-action) action like we run in the client repo and then will post the results [here](https://github.com/USSF-ORBIT/ussf-portal-cms/security/code-scanning)

ci: codeQL just like ussf-portal-client repo

---

scripts/add-rds-cas.sh

Bad copy/paste. Fixes the path so it'll download the cert.

chore: fix typo in URL

---

e2e/database/seed.js
e2e/tests/article.spec.ts
migrations/20220527214221_add_article_category/migration.sql
schema.graphql
schema.prisma
src/lists/Article.test.ts
src/lists/Article.ts

This PR adds a `category` field to the article schema, which is required select from hardcoded enums. This field is for categorizing article content at a high level to determine where on the portal it should appear. Accepted values are: `InternalNews, ORBITBlog` (more can be added).
---
Do you have any feedback re: the category names, or other categories that should be added?
---

feat: Add category field to article schema

---

src/lists/User.ts
src/util/access.test.ts
src/util/access.ts

This fixes an issue where non-admin users can only view themselves, which results in Authors & Managers not being able to see what user created or modified other resources such as Articles. This PR modifies permissions to allow users with the Author or Manager role to query (read) other users -- but still can only edit themselves.
---
Test cases:
- Admin users should be able to view and edit all other users
- Users with the Author or Manager role should be able to view all other users (but only edit themselves), _including_ the user who created or updated another object such as an Article
- Users with the User role (default) should still not be able to view any users other than themselves
* Example: log in as a Manager user and create an Article. Then log in as an Author user and view the …

fix: Allow CMS authors & managers to view other users

---

keystone.ts
schema.graphql
schema.prisma
src/lib/auth.ts
src/lib/schema.test.ts
src/lib/schema.ts
src/lib/search.ts
src/testData.ts
src/testHelpers.ts

* Adds a search query resolver to Keystone
* Returns search results for bookmarks and articles (except the body text)
* Adds a search result interface, BookmarkResult type, and ArticleResult type
* ~Do we need any other data for the search results?~ [Synced with Suz about FE requirements]
* ~We store a slug for an article, is this enough for url since we know if it's an article?~ [For now, slug is fine]
* Other style suggestions always welcome!
All database queries are using full-text search except url for Bookmarks. This is because if we want to match on part of the url, we need to use `contains`. The catch: Matching any little bit of the substring could be confusing, e.g. searching 'car' and getting a match on `tricareonline.com/`. There is probably further optimization to be done.
* …

dev: Implement search resolver

---

migrations/20220615160126_add_label_type/migration.sql
schema.graphql
schema.prisma
src/lib/schema.test.ts
src/lists/Label.test.ts
src/lists/Label.ts
src/testData.ts

Since we have 3 different UI treatments for Labels based on what kind of information the label is conveying, I added a `type` field to the Label schema. It is required since there is no default Label design, and can be one of the following options: `Source, Audience, Base`. More Label types can be added in the future as needed, but should also correspond to design updates.
---
- Verify if you log into the CMS as an admin user, you can create a Label with a type selected.
- `yarn dev` to start the CMS locally, which should also run migrations
- The migrations will fail if you already have Labels created. If this is the case you can reset your local DB with: `yarn keystone dev --reset-db` (this will delete all data from your local Keystone database). In our deployed environments, there …

feat: Add Label type field

---

.github/workflows/dev-aws-ecr.yml
scripts/snapshot-rds.sh

Like snapshotting DocumentDB for Portal-Client, this snapshots RDS (postgres) during a deploy and waits for the snapshot to exist before deploying.

chore: adding a script to snapshot RDS prior to a deploy

---

.github/settings.yml

I unchecked the box, but was unaware that this was managed here. So updating the bool to reflect that we don't want to dismiss a review.

chore: disabling the dismissal of stale reviews

---

.github/workflows/semantic-pr.yml
package.json

Like https://github.com/USSF-ORBIT/ussf-portal-client/pull/757 this adds `security` as a type for commit messages.

ci: adding security type to conventional commit

---

.github/workflows/cache-to-ecr.yml

- build docker image with cache in-line
- push image with cache to AWS ECR, allowing other workflows to utilize the cache to speed up builds
---
Once merged to Main, the workflow can be run on dispatch and tested there. There is no anticipated effect on any existing workflows.
---

ci: build docker cache and push to aws ecr

---

.github/workflows/cache-to-ecr.yml

- cache-to-ecr.yml runs too often because it is triggered on Pull Requests. Change to only trigger on Push to Main
---
---

ci: only triger cache-to-ecr on push to main

---

CHANGELOG.md
package.json

* bump moment-timezone from 0.5.34 to 0.5.37 ([#134](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/134)) ([6b37f6c](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/6b37f6ce5bef5abdcc3ec4149d768e9418bcca7f))

chore(release): 1.4.4

---

.envrc
README.md
docker-compose.e2e.yml
src/testHelpers.ts

- extend the connection timeout from CMS App to Keystone DB from the default 5 seconds to 10 seconds
This change only modifies how environment variables operates locally. In AWS, the connection string will have to be modified in AWS Systems Manager Parameter Store.
- ...

dev: extend connection timeout to keystone db

---

Dockerfile

We do this in the portal-client repo, so in the spirit of consistency, doing it here.

chore: does a dist-upgrade, ensuring we get latest packages

---

Dockerfile

We do this in the build stage of the Dockerfile, so in the spirit of consistency, doing it in the e2e and runner stage. This also gets us some package updates.

chore: add dist-upgrade to e2e and runenr stages

---

README.md

Update doc to reflect:
- need to override default Keystone CMS port
- possible errors that may occur if Postgres is running locally while keystone-db container is running

docs: update readme to include port override and postgres troubleshooting

---

CHANGELOG.md
package.json

* update undici to 5.5.1 ([#176](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/176)) ([f4b7621](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/f4b7621509d66a774cb0b68b4b1a93943596134e))
* upgrades busyboy which should update dicer ([#177](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/177)) ([732f9b6](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/732f9b6f8640cfe1834eb656a94855844490fa9c))
* update readme to include port override and postgres troubleshooting ([#185](https://github.com/USSF-ORBIT/ussf-portal-cms/issues/185)) ([5a19208](https://github.com/USSF-ORBIT/ussf-portal-cms/commit/5a1920849f757403eaa14ce5abfc57b65454a2c3))
* Revert "chore(deps): update amannn/action-semantic-pull-request action to v5 (#192)" (#198) …

chore(release): 1.4.6

---

.github/workflows/build-push-c1-art.yml
.github/workflows/cache-to-ecr.yml
.github/workflows/dev-aws-ecr.yml
.github/workflows/node-ci.yml

Replacing soon to be deprecated `set-output` with the recommendated pattern per the [docs](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

chore: replacing deprecated set-output

---

package.json
yarn.lock

- Resolves `qs` to version `6.10.3` in order to remediate[ vulnerability alert #20](https://github.com/USSF-ORBIT/ussf-portal-cms/security/dependabot/20)
---

chore: update qs to 6.10.3

---

.github/CODEOWNERS

Also resolves SC-1349
Instead of creating a PR to add or remove code owners this adds a github group to manage the same thing.
I've created PRs for this in the portal (USSF-ORBIT/ussf-portal#185), client (USSF-ORBIT/ussf-portal-client#902), and cms (this pr) repos.

build: switch CODEOWNERS to use group code-owners

---

.github/settings.yml

Enable setting to use PR title as squash merge commit message by default.

dev: update github setting to ensure pr title used for main merge messages

---

.github/workflows/build-push-c1-art.yml

- We decided to push to C1 Artifactory only when a release is published rather than every time something is pushed to Main. A manual workflow dispatch can still be used to push any branch to Artifactory.
---

ci: only push to c1 artifactory on release publication

---

renovate.json

---
- Order renovate packagerules in ascending order of importance. This is because Renovate actually evaluates every rule without stopping and allows a rule to override earlier rules. Previously they were ordered in descending order of importance.

fix: order renovate packagerules in ascending order of importance

---

.github/workflows/build-push-c1-art.yml
scripts/add-dod-cas.sh

- added a checksum file for Certs in DoD PKI CA Cert bundle from GH Secrets
- modfiy `add-dod-cas.sh` to download Cert bundle without strict TLS verification
- modify `add-dod.cas.sh` to verify the sha256 checksum of the certs that are downloaded against the checksum file to deter MITM attacks
---
The workflow `.github/workflows/build-push-c1-art.yml` was tested with a manual dispatch and the results can be seen here: https://github.com/USSF-ORBIT/ussf-portal-cms/actions/runs/4724254188/jobs/8381246053
The output of the `Add DoD Certifaction Bundle` should include this:
```
Verification successful
certificates_pkcs7_v5_11_dod_der.p7b: OK certificates_pkcs7_v5_11_dod_dod_root_ca_3_der.p7b: OK certificates_pkcs7_v5_11_dod_dod_root_ca_4_der.p7b: OK …
```

build: download ca bundle without strict cert check and verify sha256 sum

---

.github/workflows/release-please.yml

Add a workflow to automate release PR creation with [release-please GH action](https://github.com/google-github-actions/release-please-action). I left standard-version in the `package.json` and the release instructions as I'd like to see how this works first.
Probably nothing to do until this is merged and we use it for our next release.

build: add release-please to the project

---

.eslintrc.json
src/lists/Label.ts
src/lists/User.ts
src/util/access.ts
src/util/tracking.ts
startup/logging.js

This has been on my mind for a while. I made `security/detect-object-injection` as error level lint issues. This will break the build if you add any. This PR fixes a couple issues and marks the rest as accepted exceptions to that.  This PR also disabled `no-console` as a warning since we use `console` messages for server side logging. See https://eslint.org/docs/latest/rules/no-console
I am doing this because it is easy to ignore warnings and I wanted to help reduce that concern and allow us to document when we add exceptions to that. 
This is a proposal and not necessarily how we need to do things so feel free to push back on making the two lint checks error level vs warning level.
Review the fixes and any comments disabling specific lines for accuracy and clarity.
NOTE: ADR proposed for …

dev: cleanup lint warnings

---

.github/settings.yml
src/lists/Article.ts

Some times our changes don't trigger the build, for example changing documentation or github repo settings. This results in PRs being stuck due to the restrictions. There hasn't been a good way to allow these to be bypassed under certain conditions so we decided to allow admins to be able to bypass the restriction. This should be used sparingly.

chore: allow admins to bypass restrictions

---

.github/settings.yml

We have our main branch setup to restrict who can merge. Recently this means folks need to have not just `Write` access to the repo but `Maintainer` access unless granted otherwise. We were not granting any groups this permission so our designers were no longer able to merge their own PRs. This PR changes it so that members of @USSF-ORBIT/design , @USSF-ORBIT/eng , and @USSF-ORBIT/code-owners are allowed to merge PRs to main.
In an effort to grant the minimum I went this route instead of giving everyone `Maintainer` role since that adds ability to change some settings as well.
See thread https://trussworks.slack.com/archives/C025D61NNLQ/p1685991976848249

build: allow design, eng, and owners merge to main

---

schema.graphql
src/lists/LandingPage.ts

A follow up to https://github.com/USSF-ORBIT/ussf-portal-cms/pull/395 that:
- Adds the `status` field to the returned articles of a landing page
- Adds the `type` field for `labels` that are associated with an article
- Only allows published articles to link to a landing page
---
Create a landing page to test, then:
- Create two articles: one published, and one in draft.
- Give the articles the same Tag, and associate that Tag with the landing page
- Verify that you can only see the published article linked on the landing page
```sh
yarn dev
yarn dev
```
---
---

feat: Allow only published articles to link to a landing page

---

src/lists/LandingPage.test.ts
src/lists/LandingPage.ts
src/util/access.ts

- CMS Managers can update existing landing pages
---
A CMS Manager should be able to update an existing landing page. They **can't create or delete a landing page**.
When reviewing, don't forget that you will need to log in with an admin and give another user the `Manager` role to test this properly.
```sh
yarn dev
yarn dev
```
---
---

feat: Managers can update existing landing pages

---

src/lists/LandingPage.test.ts
src/lists/LandingPage.ts
src/util/access.ts

- Users with a Manager role can create landing pages
- Hide create/delete button for landing pages from users without the appropriate permissions
- Update tests
---
When testing, remember that you will need to give a CMS user the Manager role using the `cmsadmin` account
```sh
yarn dev
yarn dev
```
---
---

feat: Managers can create landing pages

---

schema.graphql
src/lib/schema.test.ts
src/lib/schema.ts
src/lib/search.ts
src/testData.ts
types.ts

- return permalink for articles. (NOTE: This currently assumes not landing page articles)
- return landing page if terms are a match in pageTitle, pageDescription, slug, or tags
---
- https://github.com/USSF-ORBIT/ussf-portal/pull/353
- https://github.com/USSF-ORBIT/ussf-portal-client/pull/1190
```sh
yarn dev
yarn dev
```
---
---

feat: landing pages show in search results

---

src/lists/Bookmark.ts
src/lists/Collection.ts
src/util/access.test.ts
src/util/access.ts

Users with a Manager role can create and update Collections and Bookmakrs
---
Log in to the CMS as a user with the Manager role and you should be able to create/update Collections and Bookmarks
- Remember that you will need to manually give a user the Manager role if you do not already have one locally
```sh
yarn dev
yarn dev
```
---
---

feat: Manager role can create/update Collections and Bookmarks

---

src/lists/Bookmark.test.ts
src/lists/Bookmark.ts
src/util/access.test.ts
src/util/access.ts

Allow managers and admins to delete bookmarks.
---
You might need to set your manager's role to manager since it's not set automatically locally.
```sh
yarn dev
yarn dev
```
---
---

fix: allow admins and managers to delete bookmarks
